---

services:
  # Backend API service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OLLAMA_DOCKER_URL=${OLLAMA_BASE_URL}
      - OLLAMA_LLM_MODEL=${OLLAMA_LLM_MODEL}
      - OLLAMA_EMBEDDING_MODEL=${OLLAMA_EMBEDDING_MODEL}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - CHROMA_COLLECTION_NAME=${CHROMA_COLLECTION_NAME}
      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
    networks:
    - internal-net
    hostname: api

  # Frontend service using CoPilotkit
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      # For container-to-container communication (backend API)
      - NEXT_PUBLIC_API_URL=http://api:8080
      - NEXT_PUBLIC_WS_URL=ws://api:8080/ws
    networks:
    - internal-net
    depends_on:
      - api
    
networks:
  internal-net:
    name: internal-net
    external: true
    driver: overlay
